version: '3.8'
services:
  octopus-web:
    build: .              # <--- This tells it to use the Dockerfile
    container_name: octopus_site_internal
    restart: always
    networks:
      - web_proxy

networks:
  web_proxy:
    external: true
