version: '3.8'
services:
  octopus-web:
    image: nginx:alpine
    container_name: octopus_site_internal
    restart: always
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - web_proxy

networks:
  web_proxy:
    external: true
